package osgi2maven.bundleImport


import org.custommonkey.xmlunit.DetailedDiff;
import org.custommonkey.xmlunit.Diff;
import org.custommonkey.xmlunit.XMLUnit;
import org.junit.Test;
import org.osgi.framework.Constants;

import osgi2maven.XmlUtils;

import static org.junit.Assert.*;


class PomTest {
	
	@Test
	public void generatePom() {
		def bundles = [new RequiredBundle(name: 'org.log4j', version: '1.5.2', visibility: Constants.VISIBILITY_PRIVATE, resolution: Constants.RESOLUTION_MANDATORY),
		new RequiredBundle(name: 'org.log4j', version: '1.5.2', visibility: Constants.VISIBILITY_PRIVATE, resolution: Constants.RESOLUTION_MANDATORY)]
		def pomText = new Pom(group: 'testGroup', artifact: 'myArtifact', version: '1.7.2a', bundles: bundles).toString()
		def expectedPom = """<?xml version="1.0" encoding="UTF-8"?>
		<!--
		Apache Maven 2 POM generated by osgi2maven
		http://wiki.github.com/mpfau/osgi2maven/
		-->
		<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
		  <modelVersion>4.0.0</modelVersion>
		  <groupId>testGroup</groupId>
		  <artifactId>myArtifact</artifactId>
		  <version>1.7.2a</version>
		  <packaging>jar</packaging>
		  <dependencies>
			<dependency>
			  <groupId>org.log4j</groupId>
			  <artifactId>org.log4j</artifactId>
			  <version>1.5.2</version>
			  <scope>compile</scope>
			</dependency>
			<dependency>
			  <groupId>org.log4j</groupId>
			  <artifactId>org.log4j</artifactId>
			  <version>1.5.2</version>
			  <scope>compile</scope>
			</dependency>
		  </dependencies>
		</project>"""
		
		XmlUtils.compareXml "The POM has not been created as expected", expectedPom, pomText
	}
	
}
